### ISSUE TITLE
Systematic Weight Variations module

### ISSUE THREAD

**Issue by benkrikler** [benkrikler/fast-carpenter-testImport#133]
**Imported from [gitlab issue 13](https://gitlab.cern.ch/fast-hep/public/fast-carpenter/issues/13)**

The current implementation is too restrictive.  Should move to something that supports this sort of config:
```yaml
systematics:                                                                       
    weights:                                                                       
        pileUp: {nominal: puWeight, up: puWeightUp, down: puWeightDown}            
        totalMuonSF: {nominal: totalMuonSF} 
```
